
-- Query: Product Performance Analysis
-- Description:
-- This query calculates total revenue generated by each product to identify top-performing products based on sales.


SELECT 
  product,
  SUM(quantity * price) AS revenue
FROM sales_table
GROUP BY product
ORDER BY revenue DESC;
